### ISSUE TITLE
Suggestion is not working for Swedish 

### ISSUE THREAD

**Issue by TharinduK97** [wooorm/dictionaries#45] opened 2022-03-09 03:52 UTC
I have used Syncfusion spellchecker with the Humspell using  Asp .net core. but I tried to get suggestions from swediish I could not receive any result, as well as spell-checking function, is not working properly. but while not using the suggestion it is working properly and both the suggestion and checking functions are working with other languages like English variants, Russian, French etc.. so is there any limitations in the Swedish dictionary ???

**Comment by wooorm** [comment] 2022-03-09 10:44
Duplicate of #35

```sh
mkdir example
npm i dictionary-svcp node_modules/dictionary-sv/index.aff sv.aff; cp node_modules/dictionary-sv/index.dic sv.dic
hunspell <<< 'a bunch of things'
```

Yields:

```
Hunspell 1.7.0
*
& bunch 2 2: brunch, lunch
& of 10 8: o, f, or, os, om, ok, ob, oh, oj, o-
& things 3 11: tings, tvings, hingst
```

^-- Seems to work.

**Closed by wooorm** 2022-03-09 10:44 UTC
