### ISSUE TITLE
Issues with 

### ISSUE THREAD

**Issue by b-pieniak** [wooorm/dictionaries#71] opened 2024-07-29 12:21 UTC
Hi, 
We have recieved information from user that terms containing "ё" in RU dictionary are being flagged as typos/errors . Could this be adjusted?

**Comment by wooorm** [comment] 2024-07-30 09:52
Duplicate of https://github.com/wooorm/dictionaries/issues/72

**Closed** 2024-07-30 09:51 UTC
